#!/bin/bash

linkTarget="/untether/expl.js"

function testStage1 {
 echo "[*] Testing stage1 exploit"
 /System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc $linkTarget
 if [ $? -eq 0 ]; then
  echo "[*] Verified stage1 works"
  return 0
 else
  echo "[!] Stage 1 does not work!"
  return 1
 fi
}

echo "[*] Installing untether"
echo "[*] Creating install helper"
touch /tmp/untetherHomeDeoptCydiaInstallHelper
testStage1
stage1ret=$?
echo "[*] Removing install helper"
rm /tmp/untetherHomeDeoptCydiaInstallHelper

if [ $stage1ret -ne 0 ]; then
  echo "[!] Stage1 exploit failed. Refusing to install!"
  echo "[!] Refusing to install"
  exit -1
fi

if [ -e /usr/libexec/rtbuddyd ];then
        echo "found rtbuddyd, backing up and symlinking..."
        if [ ! -e /usr/libexec/rtbuddyd.orig ];then
                mv /usr/libexec/rtbuddyd /usr/libexec/rtbuddyd.orig
                ln -s /System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc /usr/libexec/rtbuddyd
        else
                echo "WARNING: rtbuddyd.orig exists not modifying rtbuddyd, it's probably correct already"
        fi
else
        echo "[*] rtbuddyd doesn't exist, symlinkng jsc"
        ln -s /System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc /usr/libexec/rtbuddyd
fi
rm -f /--early-boot
ln -s $linkTarget /--early-boot
rm -f /var/logs/untetherhomedepot.log
rm -f /var/logs/untetherhomedepotLoopProtection.txt
exit 0
