#!/bin/bash
declare -a cydia
cydia=($CYDIA)

echo "Stash933 Version 1.4.8"
echo "Copyright 2016, CoolStar."
echo "stashing preference bundles..."
/usr/libexec/cydia/move.sh /Library/PreferenceBundles #Preference Bundles
/usr/libexec/cydia/move.sh /Library/PreferenceLoader #Preference Bundles
echo "stashing 3rd party binaries/libraries..."
/usr/libexec/cydia/move.sh /usr/local/bin #perl and some others
/usr/libexec/cydia/move.sh /usr/local/lib #perl and some others
echo "stashing developer toolchains..."
/usr/libexec/cydia/move.sh /usr/share/llvm #LLVM + Clang for developers
echo "Done. Enjoy your free space for tweaks!"

if mount | grep -q "/private/var (.*nosuid"; then
	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:reboot' >&${cydia[0]}"
	else
		echo "Please reboot your device after installation!"
		echo "Please reboot your device after installation!"
		echo "Please reboot your device after installation!"
		echo "Please reboot your device after installation!"
	fi
fi
exit 0